CFLAGS += -DWOLFSSL_USER_SETTINGS=1
CFLAGS += -DWOLFSSL_RIOT_OS=1

INCLUDES += -I$(APPDIR)
INCLUDES += -I$(PKGDIRBASE)/wolfmqtt
INCLUDES += -I$(RIOTBASE)/pkg/wolfmqtt/include

#ifneq (,$(filter sock_tls,$(USEMODULE)))
#  DIRS += $(RIOTBASE)/pkg/wolfssl/sock_tls
#endif

