ifneq (,$(filter wolfmqtt,$(USEMODULE))) # if module in USEMODULE
  USEMODULE += wolfssl                         # add dependencies to USEMODULE
  USEMODULE += wolfssl_internal
  USEMODULE += wolfssl_wolfio
  USEMODULE += wolfssl_keys
  USEMODULE += wolfssl_ssl
  USEMODULE += wolfssl_tls

  USEMODULE += wolfcrypt
  USEMODULE += wolfcrypt_aes
  USEMODULE += wolfcrypt_asn
  USEMODULE += wolfcrypt_hmac
  USEMODULE += wolfcrypt_md5
  USEMODULE += wolfcrypt_sha
  USEMODULE += wolfcrypt_random
  USEMODULE += posix_sockets
  USEMODULE += posix_inet

  USEMODULE += wolfmqtt_mqtt_client
  USEMODULE += wolfmqtt_mqtt_packet
  USEMODULE += wolfmqtt_mqtt_socket
  USEMODULE += wolfmqtt_mqtt_types

endif
